services:
  postgres:
    image: postgres@sha256:cf70b3d7aeb0f399ba29e94ce081380ccade1f4c38e203309068a30f49548417 # 18.2-alpine3.22
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_INITDB_ARGS: --locale=C --encoding=UTF8
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./db/better-auth.sql:/docker-entrypoint-initdb.d/better-auth.sql:ro
      - ./db/schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "psql -U postgres -d postgres -c 'SELECT 1'"]
      interval: 5s
      timeout: 3s
      retries: 6
  ollama:
    image: ollama/ollama:${GPU_FLAVOR}
    ports:
      - 11434:11434
    volumes:
      - ollama:/root/.ollama
  dex:
    image: dexidp/dex@sha256:43a8f45c0bbcd2f5e7e941c15f31b7d92fa041bd25e4c00124f021c8da25d21e
    ports:
      - 5556:5556
    volumes:
      - ./config.dex.yaml:/etc/dex/config.yaml
    command: ["dex", "serve", "/etc/dex/config.yaml"]

volumes:
  postgres:
  ollama:
  n8n:
